apiVersion: v1
kind: Service
metadata:
  name: swagger-api-service
  namespace: swaggerapp
  labels: {
    "type" : "server",
    "env" : "multi"
  }
spec:
  selector:
    component: swagger-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31516
  type: NodePort